# Generated by Django 5.1.4 on 2024-12-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='area_sq_km',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='headquarter',
            field=models.CharField(default='nice', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='website',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
    ]
