# Generated by Django 5.1.4 on 2024-12-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_district_area_sq_km_district_headquarter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='area_sq_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='province',
            name='area_sq_km',
            field=models.FloatField(),
        ),
    ]
