# Generated by Django 5.1.4 on 2024-12-17 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_municipalitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='area_sq_km',
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='municipality_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.municipalitytype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipality',
            name='website',
            field=models.CharField(default='ncie', max_length=255),
            preserve_default=False,
        ),
    ]
