# Generated by Django 5.1.4 on 2024-12-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_eventtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='organization_designation',
            field=models.CharField(blank=True, db_column='organization_designation', max_length=255, null=True),
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='organization_designation',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.TextField(default='nice addr'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ethnicity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.ethnicity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.occupation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.title'),
            preserve_default=False,
        ),
    ]
