# Generated by Django 5.1.4 on 2024-12-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_participant_organization_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertifiedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
