# Generated by Django 5.1.4 on 2024-12-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_certifiedstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.certifiedstatus'),
        ),
    ]
