# Generated by Django 5.1.4 on 2024-12-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_province_area_sq_km_province_headquarter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='area_sq_km',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='headquarter',
            field=models.CharField(default='nice', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='website',
            field=models.CharField(default='nice', max_length=255),
            preserve_default=False,
        ),
    ]
