# Generated by Django 5.1.4 on 2024-12-17 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_municipality_area_sq_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.project'),
            preserve_default=False,
        ),
    ]
