# Generated by Django 5.1.4 on 2024-12-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_projectfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(upload_to='project_files/'),
        ),
    ]
